### ISSUE TITLE
Push latest version to a mainnet account

### ISSUE THREAD

**Issue by abourget** [eoscanada/eosio.forum#16]
Setup multisig permissions with participating BPs' accounts.

/cc @chillsauce for the list of participating BPs
/cc @maoueh @errows

**Comment by abourget** [comment]
@chillsauce in Telegram:

EOS Canada
EOS Tribe
GenerEOS
TeamGreymass
EOS 42
EOS Nation

**Comment by chillsauce** [comment]
Yup - those are the ones.

Here are the BP account names for your convenience:
eoscanadacom
eostribeprod
aus1genereos
teamgreymass
eos42freedom
eosnationftw

**Comment by abourget** [comment]
@maoueh let's keep track of the progress in here (and perhaps update the README.md with the latest reality).. also we can document where things are on different testnets ! thanks :)

**Comment by abourget** [comment]
Let's put a 1/2 multisig per BP for the owner key, would that make sense to get started? Means at least 2 need to sign off.

**Comment by fproulx-eoscanada** [comment]
@abourget @chillsauce done 
https://eosq.app/account/eosforumrcpp (check the permissions tab)

**Comment by abourget** [comment]
Eventually, we can put threshold = 2 for `active` also..
