### ISSUE TITLE
Version missing from ABI

### ISSUE THREAD

**Issue by arhag** [eoscanada/eosio.forum#18]
I noticed that forum.abi is missing a `version` field. If the ABI is meant to follow the EOSIO ABI quasi-standard that clients such as cleos, abieos, and eosjs2 expect, then it needs to have the version string "eosio::abi/1.0".

While the version string may not be currently enforced in either of the aforementioned clients, they will likely be soon updated to fix that bug and enforce it as they always should have. Clients that enforce the ABI version should reject processing an ABI that declares an unsupported version, which could break functionality such as reading table rows or pushing JSON-formatted actions when interacting with contracts that have an ABI with incompatible version declared.

**Comment by maoueh** [comment]
@arhag Thanks for the heads-up, I will fix that for sure.

If you find anything else, small or large, I'll be more than happy to get your review of the contract :)

**Comment by arhag** [comment]
This was fixed with ccbd5040a7ed57e7b05b354bce62e94d8fa0a732 so I am closing the issue.

FYI: I noticed that the ABI on the `eosforumrcpp` account on the EOS blockchain was updated to include the version, but the same is not true for the `eosforumdapp` account (which I assume is associated with this contract since the README refers to it).

**Comment by maoueh** [comment]
We are going to update the README since `eosforumdapp` is the old version and not "used" anymore.
